
- name: Setup mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: copying mongodb Repo
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-repo-config

- name: installing mongodb 
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: enable remote connections to mongodb
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'



- name: enabling & starting service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes


