- name: Setup mongodb Repo
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-repo-config

- name: installing mongodb 
  ansible.builtin.yum:
    name: mongodb-org
    state: installed
    
- name: enabling & starting service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes


