- name: Configure YUM Repos from the script provided by vendor && Configure YUM Repos for RabbitMQ.
  ansible.builtin.shell:  '{{item}}'
  loop:
    - 'curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash'
    - 'curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash'

- name: Install RabbitMQ
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: Enable & Start RabbitMQ Service
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: RabbitMQ comes with a default username / password as guest/guest. But this user cannot be used to connect. Hence, we need to create one user for the application.
  # ansible.builtin.shell:  '{{item}}'
  # loop:
  #   - 'rabbitmqctl add_user roboshop roboshop123'
  #   - 'rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"'
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present