- name: Installed Mysql
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: change the default root password in order to start using the database service.
  ansible.builtin.shell: 'mysql_secure_installation --set-root-pass RoboShop@1'